apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ooc-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ooc-manager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ooc-manager
    spec:
      containers:
        - name: {{ .Release.Name }}-ooc-manager
          image: {{ .Values.oocmanager.image.repository }}:{{ .Values.oocmanager.image.tag }}
          env:
            - name: PORT
              value: {{.Values.oocmanager.port | quote}}
            - name: DB_HOST
              value: {{.Values.postgresDb.dbHost | quote}}
            - name: DB_PORT
              value: {{.Values.postgresDb.dbPort | quote}}
            - name: DB_USER
              value: {{.Values.postgresDb.dbUser | quote}}
            - name: DB_PASSWORD
              value: {{.Values.postgresDb.dbPassword | quote}}
            - name: DB_NAME
              value: {{.Values.postgresDb.dbName | quote}}
            - name: DB_SCHEMA
              value: {{.Values.postgresDb.dbSchema | quote}}
            - name: JWT_DEF_SECRET
              value: {{.Values.oocmanager.env.jwtDefSecret | quote}}
            - name: JWT_SDK_SECRET
              value: {{.Values.oocmanager.env.jwtSdkSecret | quote}}
            - name: VAULT_ADDR
              value: {{.Values.oocmanager.env.vaultAddr | quote}}
            - name: VAULT_TOKEN
              value: {{.Values.oocmanager.env.vaultToken | quote}}
            - name: AUTH_MANAGER_URL
              value: http://{{ .Release.Name }}-auth-manager.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.authmanager.port | quote }}
            - name: OAUTH_LOGIN_SERVICE_URL
              value: {{ .Values.oocmanager.env.oauthLoginServiceUrl | quote }}
            - name: HYDRA_ADMIN_URL
              value: {{ .Values.oocmanager.env.hydraAdminUrl | quote }}
            - name: HYDRA_PUBLIC_URL
              value: {{ .Values.oocmanager.env.hydraPublicUrl | quote }}
            - name: CORS_ALLOW_ORIGIN
              value: {{.Values.oocmanager.env.corsAllowOrigin | quote}}
            - name: LOG_LEVEL
              value: {{.Values.oocmanager.env.logLevel | quote}}
            - name: GIN_MODE
              value: {{.Values.oocmanager.env.ginMode | quote}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.oocmanager.port }}
      serviceAccountName: {{ .Release.Namespace }}-sa
      imagePullSecrets:
        - name: "{{ .Release.Name }}-docker-registry-secret"